USE dad_db;

INSERT INTO dads (first_name, last_name, email, username, password, favorite_joke, bio, img_url)
    VALUES
      ('Tim', 'Taylor', 'timtaylor@tooltim.com', 'The Tool Man', 'tooltime', 'jokes', 'Ever the know-it-all, Tim believes he has an incredibly wide knowledge of tools, electronics, and general mechanics. In reality, he is highly accident-prone. He actually does have a significant amount of skill as a general handyman, but can be overly confident and prone to spectacular mishaps. He often forgets a crucial step, ignores instructions, makes ill-advised modifications, or comes to inaccurate conclusions. The only exception to this ineptitude is when working on cars, at which he excels.', ''),
      ('Raymond','Barone','everybody-loves-me@aol.com','Ray Man','strong password','Puns about poop aren’t my favorite, but they’re a solid number 2','Ray is a good natured and funny guy, but definitely falls into the “incompetent man-child” stereotype currently dominating the airwaves. He’s not good at communicating, and cracks a joke instead of dealing with things seriously. He’s still tied to his mom’s apron strings and can’t confront her. While he works from home, he doesn’t spend much time with his kids and wife, preferring to watch TV. When he does spend time with his kids, he prefers his twin sons over his daughter. He’s not sure how to relate to her since she’s a girl and so buys her gifts to solve her problems or makes his wife deal with it.', ''),
      ('Noah','Levenstine','america-loves-pies@life.com','Pie Dad','superstrongpassword','I was struck by a bottle of omega 3 pills. Luckily, my wounds were only super fish oil.','Noah met his wife, got married, and settled down to a happy domestic life helping to raise their only child, Jim. Having to deal with Jim\'s awkward sexual mishaps that began in high school, Noah supported and helped Jim through them, often keeping the ones that he felt would do no harm to keep from his wife a secret.', ''),
      ('Dan','Conner','roseanneLOVESme@hotmail.com','Family Man','books4days','To the thief who took my anti-depressants: I hope you’re happy.','Dan Conner is an easy-going, hardworking father. Throughout the series he holds many occupations and is often seen balancing work, home, and personal interests. He is the typical working-class father who provides comic relief, but also is a good example for his children. He is an avid Chicago sports fan, including the Bears, Bulls, Cubs, and Blackhawks, and many of the shows make mention of the teams. He also enjoys junk food, playing poker, and fixing motorcycles with his friends. In many ways, he epitomizes the stereotypical American father and is widely considered one of the best TV dads of all time.', ''),
      ('Homer','Simpson','pink-donuts@life.com','Donut Dad','donut','Dogs can’t operate MRI scanners, but catscan.','At his job at the Springfield Nuclear Power plant, Homer is lazy, and often sleeps on duty. His favorite hobbies are watching TV and drinking at Moe\'s Tavern. His best friends are childhood pals Barney Gumble, Lenny Leonard, Carl Carlson, and Moe Szyslak. His favorite beer is Duff. Homer once pushed 15 crayons up his nose. One remains wedged in his brain, resulting in Homer\'s below low IQ. Homer Simpson developed an overeating habit after a traumatizing experience discovering a decomposing corpse.', ''),
      ('Carlton','Winslow','supercop1956@hotmail.com','Red White & Cool Dad','dadfad','I married a pirate with a patch the one eye love.','Carl is often constantly annoyed, irritated and always being bothered by his pesky neighbor, Steve Urkel, who has a very high level of respect for Carl and affectionately calls Carl ""Big Guy"". Carl is an officer for the Chicago Police Department. Fitting into the cop stereotype, he has an avid love for doughnuts and other junk food.', ''),
      ('Peter','Griffin','i-wont-remember-this@louis.com','Fonse Follwer','allHAILtheFONSE','If a parsley farmer is sued can they garnish his wages?','Peter Griffin is a lousy father. He makes fun of Chris, pays no attention to Stewie, and treats Meg like crap. His selling of Meg to pay off a debt at the local drug store is a perfect example of his failure as a dad. A father that sells his daughter into slavery deserves to be hit across the face with the baseball bat. Of course, if that happened to Peter, it would be hilarious. And probably involve some kind of wacky TV sitcom flashback.', ''),
      ('Danny','Tanner','fullhouse_happyhome@yahoo.com','Rad Dad','peopleinmyhouse99','My fear of moving stairs is escalating.','Danny is the archetype of the \"not-hip dad\" or the \"uncool\" character. He sees himself as the \"raddest, baddest\" dad ever (which his daughters do not agree with him about at all). He wants to show everyone that he has the same coolness that Jesse has. Danny is usually seen as a control freak, not by just the girls, but by the rest of the family as a whole. Danny is also obsessed with cleaning and wants to make sure there\'s no speck of dust, dirt, or mildew on anything he owns. His motto is, \"Clean is good, dirt is bad.\"', ''),
      ('Archie','Bunker','donttouch-mychiar@me.com','Chair King','hatemynieghbors33','I saw a baguette at the zoo - it was break in captivity.','Archie pretty much spent his entire time sitting in his living room chair spouting off racial epithets and calling his son-in-law “Meathead.” While Archie started to soften up as the series progressed, he was still pretty much a racist jackass.', ''),
      ('Al','Bundy','why@me.com','Dad with Children','im_right2000','This graveyard looks overcrowded. People must be dying to get in there.','Al Bundy had no redeeming qualities. He was loser who wished he could go back to his high school days when he was a football star. Sitting on the couch with his hand in his pants, he doled out criticism to his family with apathetic aplomb. He was stuck in a dead end job as a shoe salesman, and couldn’t even excel in that capacity. He was up to his ears in debt. His relationship with his kids was poor and his attitude toward women, including his wife, was deplorable. If you want a lesson on how not to be a man, live like Al Bundy.', ''),
      ('Phillip','Banks','willsgrounded99@yahoo.com','Fresh Dad','ironfist','5/4 of people admit that they’re bad with fractions.','Philip is a somewhat strict and gruff, but he does have a softer side, as he is a loving and caring family man, as well as being an upstanding citizen. Nonetheless, his anger can get him into trouble at times, especially when he feels his image is being besmirched. Additionally, Philip can be financially greedy; he pays his butler Geoffrey a salary so low that Geoffrey quits after Philip gives him a mediocre additional annual raise.', ''),
      ('Alan','Matthews','myboys@aol.com','World Dad','worldad','I would avoid the sushi if I was you. It’s a little fishy.','He has a quick temper, though when it shows up, usually through consultation with his wife, he often apologizes afterwards for words spoken in anger. He began his career as the manager of the Market Giant supermarket, eventually winning a prized ""Grocie"" Award. Prior to his marriage, Alan joined the United States Navy instead of enrolling in college after high school, a decision he is regretting and glad that his children did not made the same choice. ', ''),
      ('Maxwell','Sheffield','nannyboss@rich.com','Money Dad','cashforcleaning','I thought about going on an all-almond diet. But that\'s just nuts','Maxwell has three children, Maggie, Brighton, and Gracie, however, his busy schedule does not allow him much time to spend with them, so he had to find a nanny. Before Fran came along, Brighton had caused 3 to quit by faking his own suicide with a toy knife and ketchup.', ''),
      ('Andy','Griffith','fishing101@aol.com','Fish Dad','fishfishfish','The rotation of earth really makes my day.','As a single dad, Sheriff Taylor did a fantastic job raising his son Opie. In every episode, Sheriff Andy taught his son and the rest of America one important lesson- do the right thing. Not only did Andy teach little Opie important life lessons, he also made sure to spend plenty of time with him on fishin’ trips.', ''),
      ('Red','Forman','mysonsadumbass@mysonsadumbass.com','Red Boss','dumbass','Graveyards are always overcrowded. People must be dying to get in there.','Red is the perpetually disgruntled, ill-tempered father of Eric and Laurie and Kitty\'s husband as well as the foster father to Steven Hyde. His relationship with his children is complex. Although he dotes on his lying, manipulative, promiscuous daughter, Laurie (with whom, tellingly, Kitty has a strained and contentious relationship), he points out Eric\'s perceived flaws and faults mercilessly. The two clash in most episodes with Eric teasing his father, or \"poking the bear\". Red frequently threatens to \"stick my foot up your ass\" to Eric but is never seen physically disciplining his son, usually punishing him with chores, fines, and, once, by imposing a strict curfew, which leads to windows being nailed shut, bed checks, etc. until Kitty calls an end to it.', '');