USE dad_db;

INSERT INTO users (first_name, last_name, email, username, password, favorite_joke, bio, img_url)
VALUES
  ('Tim', 'Taylor', 'timtaylor@tooltim.com', 'The Tool Man', '$2a$10$Njyv2qyIKxcQUJo6ZdWNWe41.0hKeSQr9u8E0nDAE0tXBX7kfdfxW', 'jokes', 'Ever the know-it-all, Tim believes he has an incredibly wide knowledge of tools, electronics, and general mechanics. In reality, he is highly accident-prone. He actually does have a significant amount of skill as a general handyman, but can be overly confident and prone to spectacular mishaps. He often forgets a crucial step, ignores instructions, makes ill-advised modifications, or comes to inaccurate conclusions. The only exception to this ineptitude is when working on cars, at which he excels.', ''),
  ('Raymond','Barone','everybody-loves-me@aol.com','Ray Man','$2a$10$Njyv2qyIKxcQUJo6ZdWNWe41.0hKeSQr9u8E0nDAE0tXBX7kfdfxW','Puns about poop aren’t my favorite, but they’re a solid number 2','Ray is a good natured and funny guy, but definitely falls into the “incompetent man-child” stereotype currently dominating the airwaves. He’s not good at communicating, and cracks a joke instead of dealing with things seriously. He’s still tied to his mom’s apron strings and can’t confront her. While he works from home, he doesn’t spend much time with his kids and wife, preferring to watch TV. When he does spend time with his kids, he prefers his twin sons over his daughter. He’s not sure how to relate to her since she’s a girl and so buys her gifts to solve her problems or makes his wife deal with it.', ''),
  ('Noah','Levenstine','america-loves-pies@life.com','Pie Dad','$2a$10$Njyv2qyIKxcQUJo6ZdWNWe41.0hKeSQr9u8E0nDAE0tXBX7kfdfxW','I was struck by a bottle of omega 3 pills. Luckily, my wounds were only super fish oil.','Noah met his wife, got married, and settled down to a happy domestic life helping to raise their only child, Jim. Having to deal with Jim\'s awkward sexual mishaps that began in high school, Noah supported and helped Jim through them, often keeping the ones that he felt would do no harm to keep from his wife a secret.', ''),
  ('Dan','Conner','roseanneLOVESme@hotmail.com','Family Man','$2a$10$Njyv2qyIKxcQUJo6ZdWNWe41.0hKeSQr9u8E0nDAE0tXBX7kfdfxW','To the thief who took my anti-depressants: I hope you’re happy.','Dan Conner is an easy-going, hardworking father. Throughout the series he holds many occupations and is often seen balancing work, home, and personal interests. He is the typical working-class father who provides comic relief, but also is a good example for his children. He is an avid Chicago sports fan, including the Bears, Bulls, Cubs, and Blackhawks, and many of the shows make mention of the teams. He also enjoys junk food, playing poker, and fixing motorcycles with his friends. In many ways, he epitomizes the stereotypical American father and is widely considered one of the best TV dads of all time.', ''),
  ('Homer','Simpson','pink-donuts@life.com','Donut Dad','$2a$10$Njyv2qyIKxcQUJo6ZdWNWe41.0hKeSQr9u8E0nDAE0tXBX7kfdfxW','Dogs can’t operate MRI scanners, but catscan.','At his job at the Springfield Nuclear Power plant, Homer is lazy, and often sleeps on duty. His favorite hobbies are watching TV and drinking at Moe\'s Tavern. His best friends are childhood pals Barney Gumble, Lenny Leonard, Carl Carlson, and Moe Szyslak. His favorite beer is Duff. Homer once pushed 15 crayons up his nose. One remains wedged in his brain, resulting in Homer\'s below low IQ. Homer Simpson developed an overeating habit after a traumatizing experience discovering a decomposing corpse.', ''),
  ('Carlton','Winslow','supercop1956@hotmail.com','Red White & Cool Dad','$2a$10$Njyv2qyIKxcQUJo6ZdWNWe41.0hKeSQr9u8E0nDAE0tXBX7kfdfxW','I married a pirate with a patch the one eye love.','Carl is often constantly annoyed, irritated and always being bothered by his pesky neighbor, Steve Urkel, who has a very high level of respect for Carl and affectionately calls Carl Big Guy. Carl is an officer for the Chicago Police Department. Fitting into the cop stereotype, he has an avid love for doughnuts and other junk food.', ''),
  ('Peter','Griffin','i-wont-remember-this@louis.com','Fonse Follwer','$2a$10$Njyv2qyIKxcQUJo6ZdWNWe41.0hKeSQr9u8E0nDAE0tXBX7kfdfxW','If a parsley farmer is sued can they garnish his wages?','Peter Griffin is a lousy father. He makes fun of Chris, pays no attention to Stewie, and treats Meg like crap. His selling of Meg to pay off a debt at the local drug store is a perfect example of his failure as a dad. A father that sells his daughter into slavery deserves to be hit across the face with the baseball bat. Of course, if that happened to Peter, it would be hilarious. And probably involve some kind of wacky TV sitcom flashback.', ''),
  ('Danny','Tanner','fullhouse_happyhome@yahoo.com','Rad Dad','$2a$10$Njyv2qyIKxcQUJo6ZdWNWe41.0hKeSQr9u8E0nDAE0tXBX7kfdfxW','My fear of moving stairs is escalating.','Danny is the archetype of the not-hip dad or the uncool character. He sees himself as the raddest, baddest dad ever (which his daughters do not agree with him about at all). He wants to show everyone that he has the same coolness that Jesse has. Danny is usually seen as a control freak, not by just the girls, but by the rest of the family as a whole. Danny is also obsessed with cleaning and wants to make sure there\'s no speck of dust, dirt, or mildew on anything he owns. His motto is, Clean is good, dirt is bad.', ''),
  ('Archie','Bunker','donttouch-mychiar@me.com','Chair King','$2a$10$Njyv2qyIKxcQUJo6ZdWNWe41.0hKeSQr9u8E0nDAE0tXBX7kfdfxW','I saw a baguette at the zoo - it was break in captivity.','Archie pretty much spent his entire time sitting in his living room chair spouting off racial epithets and calling his son-in-law “Meathead.” While Archie started to soften up as the series progressed, he was still pretty much a racist jackass.', ''),
  ('Al','Bundy','why@me.com','Dad with Children','$2a$10$Njyv2qyIKxcQUJo6ZdWNWe41.0hKeSQr9u8E0nDAE0tXBX7kfdfxW','This graveyard looks overcrowded. People must be dying to get in there.','Al Bundy had no redeeming qualities. He was loser who wished he could go back to his high school days when he was a football star. Sitting on the couch with his hand in his pants, he doled out criticism to his family with apathetic aplomb. He was stuck in a dead end job as a shoe salesman, and couldn’t even excel in that capacity. He was up to his ears in debt. His relationship with his kids was poor and his attitude toward women, including his wife, was deplorable. If you want a lesson on how not to be a man, live like Al Bundy.', ''),
  ('Phillip','Banks','willsgrounded99@yahoo.com','Fresh Dad','$2a$10$Njyv2qyIKxcQUJo6ZdWNWe41.0hKeSQr9u8E0nDAE0tXBX7kfdfxW','5/4 of people admit that they’re bad with fractions.','Philip is a somewhat strict and gruff, but he does have a softer side, as he is a loving and caring family man, as well as being an upstanding citizen. Nonetheless, his anger can get him into trouble at times, especially when he feels his image is being besmirched. Additionally, Philip can be financially greedy; he pays his butler Geoffrey a salary so low that Geoffrey quits after Philip gives him a mediocre additional annual raise.', ''),
  ('Alan','Matthews','myboys@aol.com','World Dad','$2a$10$Njyv2qyIKxcQUJo6ZdWNWe41.0hKeSQr9u8E0nDAE0tXBX7kfdfxW','I would avoid the sushi if I was you. It’s a little fishy.','He has a quick temper, though when it shows up, usually through consultation with his wife, he often apologizes afterwards for words spoken in anger. He began his career as the manager of the Market Giant supermarket, eventually winning a prized Grocie Award. Prior to his marriage, Alan joined the United States Navy instead of enrolling in college after high school, a decision he is regretting and glad that his children did not made the same choice. ', ''),
  ('Maxwell','Sheffield','nannyboss@rich.com','Money Dad','$2a$10$Njyv2qyIKxcQUJo6ZdWNWe41.0hKeSQr9u8E0nDAE0tXBX7kfdfxW','I thought about going on an all-almond diet. But that\'s just nuts','Maxwell has three children, Maggie, Brighton, and Gracie, however, his busy schedule does not allow him much time to spend with them, so he had to find a nanny. Before Fran came along, Brighton had caused 3 to quit by faking his own suicide with a toy knife and ketchup.', ''),
  ('Andy','Griffith','fishing101@aol.com','Fish Dad','$2a$10$Njyv2qyIKxcQUJo6ZdWNWe41.0hKeSQr9u8E0nDAE0tXBX7kfdfxW','The rotation of earth really makes my day.','As a single dad, Sheriff Taylor did a fantastic job raising his son Opie. In every episode, Sheriff Andy taught his son and the rest of America one important lesson- do the right thing. Not only did Andy teach little Opie important life lessons, he also made sure to spend plenty of time with him on fishin’ trips.', ''),
  ('Red','Forman','mysonsadumbass@mysonsadumbass.com','Red Boss','$2a$10$Njyv2qyIKxcQUJo6ZdWNWe41.0hKeSQr9u8E0nDAE0tXBX7kfdfxW','Graveyards are always overcrowded. People must be dying to get in there.','Red is the perpetually disgruntled, ill-tempered father of Eric and Laurie and Kitty\'s husband as well as the foster father to Steven Hyde. His relationship with his children is complex. Although he dotes on his lying, manipulative, promiscuous daughter, Laurie (with whom, tellingly, Kitty has a strained and contentious relationship), he points out Eric\'s perceived flaws and faults mercilessly. The two clash in most episodes with Eric teasing his father, or poking the bear. Red frequently threatens to stick my foot up your ass to Eric but is never seen physically disciplining his son, usually punishing him with chores, fines, and, once, by imposing a strict curfew, which leads to windows being nailed shut, bed checks, etc. until Kitty calls an end to it.', '');

INSERT INTO the_meats (users_id, the_meat, time, location, dadscription)
VALUES
  ('15','Brisket and Sausage','7:00:00 AM','Next to the big tree.','Wanted to share a new recipe with other Dads in the area. Can someone bring charcoal?'),
  ('3','Smoking Brisket','5:00:00 AM','My front yard. Follow the loud music.','I will be smoking a 20lb brisket that my buddy got me this Friday. Anyone who can help us lift it to turn it can eat some when it is done.'),
  ('2','Swineapple','3:00:00 PM','Neighborhood Park.','I found a recipe for a Swineapple. I have never tried pork inside of a pineapple and my family will not try it with me.'),
  ('6','Spicy Kiolbassa','11:00:00 AM','Behind the courthouse.','Never had spicy food and I want to cook some. Come make sure that I don\'t die please.'),
  ('7','Rack of Lamb','3:00:00 AM','15 minutes from the main highway.','My wife wants me to cook this lamb. I dont know how to cook lamb but I figure that it would take all day. Someone help and bring some spices please.'),
  ('9','Briskets','7:00:00 AM','New office downtown.','I volunteered to BBQ for my office friends but Ive never grilled before. Help?'),
  ('10','Backstrap','8:00:00 AM','Outskirts of hunting zone.','Looking for people to share my first kill of deer season with!'),
  ('11','Turkey','9:30:00 AM','Back of new neighborhood.','I bought a 30lb turkey to grill because my wife wont cook me one since its not Thanksgiving. This turkey is too big. Someone come help to eat it?'),
  ('14','Brisket','11:00:00 AM','My house.','I dont want to share my brisket. I just wanted to let you know that Im grilling.'),
  ('13','Goat','7:00:00 AM','Old swimming hole.','I shot a goat wondering around on my land because I wanted to know what it tastes like. Should I have killed it to eat it? Is this illegal? If this is okay, someone come help me. If this was a bad idea, you never saw this post...'),
  ('4','Hog Meat','8:00:00 AM','We could meet up somewhere.','My neighbor had a hog problem and, long story short, I have hog meat. Anyone want in?'),
  ('5','Pork Ribs','1:00:00 PM','Neighborhood Park.','Looking for anyone to try these ribs with my homemade BBQ sauce. It has a good kick so dont try it if you dont like spicy stuff. This will put a lot of hair on your chest.'),
  ('8','Any Kind','3:00:00 PM','Next to new park.','I dont have meat to cook but my cousin just sent me a new BBQ sauce flavor to try. Ill split it with you if I can have some of what youre cooking.'),
  ('12','Pork Chops','9:30:00 AM','Company Venue','I invited my employees to a company cook out and nobody showed. I cooked a lot of food so if you show up with some beers we could eat and talk about sports.'),
  ('1','Tri Tip','5:00:00 AM','10min away from downtown','My daughter showed me a video of how this meat turns out after its been smoked for a few hours. I dont want to mess it up by cooking it wrong or using the wrong seasonings. Meet up and help and you can have some.');


INSERT INTO new_balance (users_id, title, dadscription)
VALUES
  ('7','20% off on 624!','A buddy of mine that works at the New Balance store up the highway told me that the 624 model is going to go down in price by 20% It was a hush-hush inside secret, but I know that I can trust you guys. Mark your calendars for the 15th to save some money on these bad boys!'),
  ('5','Review of the 608v4','One of my favorite models thus far. The tread makes a squeaky suction noise when walking on smooth surfaces so you know its perfect for me. Had some trouble finding a wide in this style though.'),('12','806 too sporty?','Hey buds! Ive been looking into getting one of the newer models, the 806, but is it too much for me? I dont like being too flashy and you guys know me. Should I give these puppies a try?'),
  ('2','Black 624','My kids recently started saying that I dress like a dad whatever that means. So I traded in the 624s for the full black model. I cant wait for my kids to see how much cooler I look!'),
  ('6','3000v4 good to go!','I didnt like the new style that the 3000v4 had but I do like the extra added touch with the shoelace shield. It gives the shoe a clean look when you are on the field. Definitely recommend!'),
  ('11','990v4 in a wide','My 990v4 finally passed away after a soliid 10 year run. Im trying to find an identical pair but all the associates tell me that its discontinued. There has to be at least one pair somewhere!'),
  ('10','608v4 on the small side!','I wear an 11 2e in previous NB. I loved the looks and price of these, and the reviews said they were true to size. When I put these on it felt like I had 4 pair of socks on trying to squeeze my foot in them.'),
  ('4','Maintenance on the 928v3','Its a shoe that i have been looking at for a while, but Ive never had to care for a leather shoe. How hard is it to keep clean compared to a normal shoe?'),
  ('1','Discontinued 3000?','I heard the sales associates talking about how the 3000 model was going to discontinue the brown style. They will keep the black and bolt blue until further notice.'),
  ('7','Bigger savings on 624!','I read the post from someone else that the 624 was going to go down by 20%. I asked around the NB den and it turns out that the 624 is actually going to go down by 35%! I might by two pairs because the deal is so good! Ill never wear another shoe again!'),
  ('3','A 498 copy?','As we all know, the 498 Gold Edition has been discontinued for a few years. But I came across a site that sells them and ships them from overseas! Does this sound right? Should I grab them before its too late?'),
  ('9','989 best for hiking','When for a walk this past weekend with my kids so I wore my new 989 hiking shoes and they felt great! My kids gave me some looks for wearing them but what do they know..'),
  ('15','627v2 up for debate again','Guys, I hate to bring this rumor back up, but I heard that the 627v2 was finally going to get the extra padded insoles that weve been waiting five years for! I dont have any sources just a gut feeling. I think NB will finally do us right!'),
  ('14','Someone stole my 608v4s!','I left them outside so they could air dry after I cleaned them. When I came back 40mins later to check on them, they were gone! I have a new neighbor that just moved in across the street and he was eyeballing my shoes big time. Let me know if you find them! They have my initials on the bottom.'),
  ('8','623v3 back?','I saw some guy walking to his car wearing a 623v3. They looked brand new! He didn\'t want to tell me where he got them but they must be back in circulation again! When I find out where to get them, I will keep you guys posted.');

INSERT INTO new_dads (users_id, title, dadscription)
VALUES
  ('15',	'Toddler a Light Sleeper',	'My kid wakes up at the drop of a pin. Everytime I try to watch the game he wakes up. I dont want to watch it on mute because it takes away from the game. Any ideas?'),
  ('4',	'Passing Time with Baby',	'The wife says that Im in charge of the baby while she has a girls night. I got in trouble for drawing on the baby\'s face while she was sleeping. Are there any other fun things that I can do?'),
  ('11',	'SMELLY DIAPER',	'This kids is going to ruin my paint on the walls! No matter what I feed him, his diaper melts my nose. I put a car air freshener taped to the back of his butt and it seems to be working. You guys should try this!'),
  ('10',	'Jokes for Baby',	'My 2 month old seems to like my fart jokes. The wife doesn\'t think its funny but the baby cracks up.'),
  ('2',	'While the Wife is Away',	'Here at home with the baby while my wife goes shopping used to be boring but ever since I found out that he likes to watch football, this is how we bond. Give it a try and see if you can have a football baby too!'),
  ('9',	'Helping Him Roll',	'The baby is at the age where he should be trying to roll on his stomach but he hasn\'t tried yet. I thought that he was a little slow at this because he has no one to show him and I was right! As of last week, I started showing him how to roll over by showing him how I do it. After he watches me do it for about 30mins, he seemed like he was interested!'),
  ('5',	'Team Spirit',	'How small do jerseys come in? The wife said that 2 days is too young but I want to prove her wrong and show the world who my new son roots for during football season!'),
  ('1',	'Baby Moustache',	'It\'s all fun and games to draw a moustache on the baby while the wife is out at the store until you find out that you used a permanent marker..'),
  ('8',	'Cereal Sleep Challenge',	'While the baby is sleeping see how many pieces of Cheerios you can stack on his nose. Its the newest internet challenge and it\'s a lot harder than you think. I got to 10 and it only took an hour.'),
  ('14',	'Family Photo with Diapers',	'If you\'re wanting to take a family portrait style photo with you, your wife and the baby, make sure your baby is in a diaper. The photographer and your wife will try to talk you out of it, but trust me. If you give in, just make sure you wear a shirt that you don\'t mind throwing away..'),
  ('12',	'Dog and Baby',	'Ive had a golden retriever at home for 5 years now and he isn\'t scared of anything but my baby. I think it\'s the high pitched crying that he doesn\'t like.. Any tips on how to make my baby more dog friendly? '),
  ('3',	'Walking Baby Finding Trouble',	'My child has started walking.. into trouble. She walks face first into walls and chairs and I can\'t keep up. So to help me, I put about 4 pairs of pants on her to slow her down and that seems to be doing the trick!'),
  ('13',	'Tough Diapers',	'I\'m looking for tough grade diapers. The brand that we currently use is not as durable as it needs to be. After a meal of solid foods, the baby leaves..diaper prints.. around the house. Any brand suggestions?'),
  ('7',	'Toddler Time Out',	'While I was at work, my wife said that our 4yr old broke a vase on purpose. She left the punishment for me to deal with because she knows he moves too much to stay in time-out. I came across a dad on the internet who duct tapped his kid to wall for a little bit to keep him still. I think the kid actually had fun instead of being in trouble. Im going to try it out anyway because it looks cool. I\'ll let you guys know how it goes.'),
  ('6',	'Don\'t Shave',	'I\'ve been growing out my beard since my wife got pregnant. Now that Im starting a new job a year later, I had to shave. But my son DID NOT LIKE my face with no beard. He got scared and didn\'t want to look at me. What happened?');

INSERT INTO thingamajig (users_id, title, dadscription)
VALUES
  ('2','Who is Alexa?','Im pretty sure my son is hiding his girlfriend from me. I hear him talk to someone called Alexa in his room all the time but I never see her... Is it a game nowadays to hide your girlfriends from your parents?'),
  ('8','What does WiFi Stand for?','My kids are always sending me letters to my phone like LOL and IDK. They told me to check the WIFI this morning but what does it stand for?'),
  ('1','Which Post Office Has My Email?','My niece said she keeps sending me emails but the Post Office said they have no mail for me. Where else can I go?'),
  ('12','Internet on My Phone','Someone at the grocery store told me to check the internet on my phone for coupons. I cant find a spot to plug in the internet cable to my phone! Do I have the wrong model of phone?'),
  ('5','Whats A Meme?','I heard my teen talk last night about how memes keep her alive.. I need to know how harsh of a drug this is. Im so worried about her..'),
  ('15','Cost Per Email','I did some asking around and now I finally understand what my kids mean when they say that they\'ve internet mailed me something. I want to mail them back but how much does it cost per internet mail? '),
  ('11','Which Rapper is Hashtag?','Im a bus driver so I listen to kids talk all day. I hear them say Hashtag almost every other word. Which rapper is this? I want them to know that Im cool so I can talk about that Hashtag too!'),
  ('4','Face Book People','I don\'t know how, but somehow Facebook knows all about me! My daughter made an account and she was asking me all these questions like my date of birth and where I went to high school and now, all of a sudden, Facebook knows all of these things! I wont let them steal my information!'),
  ('10','Spam Not Cool?','My son suddenly doesn\'t like spam? He always ate it growing up, but now he says that my internet mail is full of it and he doesn\'t like it. Is this supposed to be some sort of new diet or something?'),
  ('13','Wheres My Password','I made a password for my email and now I cant find it. The email people should be able to give it to me, right? They cant expect me to remember something so silly.'),
  ('3','I cant Face Book with My Son','My son wants to show me his new place since he recently moved up north. He said he wants to Face Book with me but my camera wont turn on. Something about the time? Face..time? Help!'),
  ('14','Can I record Judge Judy on my Tablet?','I got a tablet for Xmas and the kids like to see me use it, even though watching normal TV is easier for me. Can I record on this thing? I don\'t want to miss my rerun of Judge Judy at 12:30 but I cant find the record button.'),
  ('9','I Was Identity Stolen!','When I first signed up for Netflix, they made me tell them what shows I like to watch. But now that\'s all the shows that I see! Did Netflix steal my identity from knowing the shows I watch? Who do I call??'),
  ('7','Strangers Online After My Kids?','My daughter said she found an old high school friend on Book Face. But how do I know that its really her friend and not a stranger after her identity? Should I ground her??'),
  ('6','Ill Be Rich Soon!','A princess sent me an email saying that she needed my help because she lost everything. She told me a very sad personal story that I wont share because I promised her that I wouldn\'t. But after I help her, she said that she would set me up good for life! After I wire her the 2 thousand that she needs to get back on her feet, Ill be living the high life!');

INSERT INTO exercise (users_id, title, location, dadscription)
VALUES
  ('8','Kid Push Ups','Park this Saturday','The kids want to go to the park and I really wanted to start working out again. So I figured that we could do both! Im going to take the kids to the park, but Ill have them climb on my back while I do a good amount of reps! Anyone want to join in? You can bring the kids!'),
  ('10','Bench Press the Baby','Anywhere','My 8 month old loves when I toss her into the air and catch her. If you try this while youre laying down she feels a little heavier and this will work out your biceps more. Happy lifting, Dads!'),
  ('1','Indoor Cardio','Inside the house','I started getting cabin fever when I couldnt go out for walks since we had the baby. But now that shes at the stage of where she throws her toys everywhere Im getting great cardio inside walking back and forth as she throws down the toys again.'),
  ('13','Eat Right','Your Kitchen','With the kids around, all I want to do is snack with them all the time but that wasnt helping my diet. Instead, what you should do is eat your kids healthy snacks like Cheerios and fruits. Leave the chocolate stuff for your wife to gain weight.'),
  ('3','Unfair Jog','Around the Fountain','I used to be a jogger before the kids. Now that my son is almost 5 he thinks hes a big kid and wants to race me. I use this opportunity to get my jogging back into my day. he never wins a race but hell never have a fat dad.'),
  ('9','Sports with the Kids','Tennis Court Past the Highway','The kids wanted to play some sports with me but Im always afraid that Ill be too rough because I get competitive. I found that if you take them to the tennis court you can  practice your swing on a bucket of tennis balls while the kids think that chasing after the balls that go flying is the best game ever.'),
  ('6','Exercise for Pulled Back?','YMCA','My granddaughter was over and I pulled something in my back while we were playing tea party because now Im pretty stiff. I think some stretches will do the trick, but any other suggestions?'),
  ('15','The Ol Fashined Way','Your Yard','Summer is here and everyone wants to stay in shape. Dont forget that we have yards to care for, fellas! Too many of you guys let your yard go last summer, so lets stay in shape by sweating while we keep our grass trimmed.'),
  ('2','Workout Tapes','Meetup?','I cleaned out the garage this weekend and found my old Richard Simmons workout tape. My kids got rid of my VHS player, are there any good DVD copies of this that anybody doesnt want?'),
  ('12','Free This Weekend!','Big Oak Tree','The wife and kids are headed to the in-laws this weekend so I finally have a chance to workout with some of the guys! Ill have on the headband that has the US flag on it with the 608NB shoes. Come find me!'),
  ('14','Just an Idea','Maybe YMCA','This post isnt asking anything, I just had an idea to share. There should be a gym that has a daycare center in there! That way Dads can workout and not worry about leaving the kids anywhere. Does this exist already?'),
  ('4','Funny Weights','WalMart','Im on the lookout for some cool looking hand weights. Maybe something like donut looking ones or hamburger buns or something. I cant find it at WalMart but I figure that they would be the place to have it.'),
  ('5','Mall Walking','Northwest Galleria','Its too hot for me to try to exercise outside. I started fast walking at the mall and its so much better since its cooler in there. If anyone wants to join me, find me pacing back and forth infront of JcPenny.'),
  ('11','Treadmill Endurance','South Park Mall','Me and a few other guys started going to the exercise place that just opened up at the end of town. They have crazy high tech machines in there! Weve started doing a competition to see who can run the fastest the longest. So far Im winning. See if you can beat my 6mph for 8min record.'),
  ('7','Hide and Seak with Kids','Anywhere','This post is about exercise for your kids instead of us Dads. I really wanted to rest yesterday afternoon but the kids wanted to play some games with their old man. I suggested a game of hide and seak. They looked for me for a full hour and declared me hide and seek champion while I just hide in the closet and took a nap.');